### ISSUE TITLE
how to fix the "cabal install" error?

### ISSUE THREAD

**Issue by luckypoem** [LeviSchuck/levischuck.com#1]
hi

root@AR:/usr/local/levischuck.com# cabal sandbox init
root@AR:/usr/local/levischuck.com# cabal install
it shows:
...
Configuring levischuck-0.1.0.0...
Building levischuck-0.1.0.0...
Preprocessing executable 'levischuck' for levischuck-0.1.0.0...
[1 of 1] Compiling Main             ( src/Main.hs, dist/dist-sandbox-58db2368/build/levischuck/levischuck-tmp/Main.o )

src/Main.hs:214:38: error:
    • Couldn't match type ‘unordered-containers-0.2.7.2:Data.HashMap.Base.HashMap
                             text-1.2.2.1:Data.Text.Internal.Text
                             aeson-1.1.0.0:Data.Aeson.Types.Internal.Value’
                     with ‘M.Map [Char] a1’
      Expected type: M.Map [Char] a1
        Actual type: Metadata
    • In the second argument of ‘M.member’, namely ‘metadata’
      In the expression: "mathjax" `M.member` metadata
      In the second argument of ‘($)’, namely
        ‘if "mathjax" `M.member` metadata then
             "<script type=\"text/javascript\" src=\"http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML\"></script>"
         else
             ""’

src/Main.hs:220:35: error:
    • Couldn't match type ‘unordered-containers-0.2.7.2:Data.HashMap.Base.HashMap
                             text-1.2.2.1:Data.Text.Internal.Text
                             aeson-1.1.0.0:Data.Aeson.Types.Internal.Value’
                     with ‘M.Map [Char] a0’
      Expected type: M.Map [Char] a0
        Actual type: Metadata
    • In the second argument of ‘M.member’, namely ‘metadata’
      In the expression: M.member "tweets" metadata
      In the second argument of ‘($)’, namely
        ‘if M.member "tweets" metadata then
             "<script async src=\"//platform.twitter.com/widgets.js\" charset=\"utf-8\"></script>"
         else
             ""’
cabal: Leaving directory '.'
cabal: Error: some packages failed to install:
levischuck-0.1.0.0 failed during the building phase. The exception was:
ExitFailure 1

**Comment by LeviSchuck** [comment]
This is now fixed.
Hakyll API changed.

Also made it so that CSS generation runs inside the cabal sandbox.

**Comment by luckypoem** [comment]
hi.

cd /usr/local
git clone https://github.com/LeviSchuck/levischuck.com
cd  levischuck.com

root@AR:/usr/local/levischuck.com# cd src
root@AR:/usr/local/levischuck.com/src# ls  
Main.hs  
root@AR:/usr/local/levischuck.com/src# ghc --make Main.hs  
 root@AR:/usr/local/levischuck.com/src# cp Main ..
 root@AR:/usr/local/levischuck.com/src# cd ..
 root@AR:/usr/local/levischuck.com# ./Main build 
it shows:
...
[ERROR] Hakyll.Core.UnixFilter.unixFilterWith: cabal exec -- runghc gave exit code 1
root@AR:/usr/local/levischuck.com# 

how to fix the ERROR?
